---
title: "git_00"
author: "Renelyn Wilson"
date: "Year 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

I painted her a gushing thing,

With years about a score;

I little thought to find they were

A least a dozen more;

My fancy gave her eyes of blue,


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,

Some say in ice.

From what I've tasted of desire

I hold with those who favor fire.

But if it had to perish twice,

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,

Shining with all his might:
      
He did his very best to make

The billows smooth and bright 
      
And this was odd, because it was

The middle of the night.

The moon was shining sulkily,

Because she thought the sun
      
Had got no business to be there

After the day was done —
      
"It's very rude of him," she said,

"To come and spoil the fun.


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

FOR her this rhyme is penned, whose luminous eyes,

Brightly expressive as the twins of Lœda,

Shall find her own sweet name, that, nestling lies

Upon the page, enwrapped from every reader.

Search narrowly the lines! — they hold a treasure

Divine — a talisman — an amulet

That must be worn at heart. Search well the measure —

The words — the syllables! Do not forget

The trivialest point, or you may lose your labor!

And yet there is in this no Gordian knot

Which one might not undo without a sabre,

If one could merely comprehend the plot.

Enwritten upon the leaf where now are peering

Eyes scintillating soul, there lie perdus

Three eloquent words oft uttered in the hearing

Of poets, by poets — as the name is a poet's, too.

Its letters, although naturally lying

Like the knight Pinto — Mendez Ferdinando —

Still form a synonym for Truth. — Cease trying!

You will not read the riddle, though you do the best you can do.


